---
title: "CEWIL 2: Workshop"
output: github_document
---

### Data Acquisition and Organization Class

Create an account for Team GPT - note that at least one student had problems with logging in using GitHub.

Join the [MtA CEWIL Project workspace](https://app.team-gpt.com/workspace/mount-allison-university/) from the invitation sent to your email.

Team GPT allows us to use both Anthropic Claude 3.5 Sonnet and OpenAI GPT-4o. Try both and see if you get better responses with one or the other.

We can also create Custom Instructions, which are personas for the AI.

We can create Prompts to do specific tasks. I have a follow-up meeting with Team GPT to talk about these tasks.

#### Overall goal

Our goal for this project is to find out if we can use AI to convert the HTML for *TAC* articles into the metadata schema required by the OJS Native XML plugin.

#### Known Limitations

You will have to copy and paste HTML and XML into the prompt. The file upload is limited to image files.

#### Today

15-20 minutes: working on your own or in pairs, create a Custom Instruction. Who is the imaginary assistant you'd want for this task? A professor? A data scientist? An experienced programmer? Write a description of this person and the kind of help you want them to give you. Try the same chat with different assistants.

10 minutes: discussion

15-20 minutes: try working with the prompts created for us by Team GPT

10 minutes: discussion

#### Outside of class

Spend some time working towards our end goal. Work on learning html or xml, experimenting with custom instructions or prompts.

#### Reminder

Please be very aware of the AI policies and expectations in other classes. Do not use Team GPT for classes unless your professors have asked you to experiment with generative AI. We're working on a learning experiment in this class, and as part of that we're assessing this tool. We might end up finding out that it doesn't save us time, or that we're not learning as quickly or deeply as if we'd used a tutorial or app or book designed by a knowledgeable human. There are also serious ethical, environmental, and social reasons not to use AI... if you want readings or critical material on the topic, let me know!

### Research and Communication Class

Today you will use the test journal to add an article from *Theory and Application of Categories* to Volume 42.

#### Create groups

Rearrange room for small group work (teams of 2 or 3 people) and we'll assign an article number from Volume 42 to each group.

Suggestion on how to work together: one person copies and pastes metadata the Quick Submit plugin, the other person checks details on the article page, adds questions to the whiteboard, and looks up information.

#### Sign in to test journal

<https://pkp.sfu.ca/software/ojs/demo/>

**Username:** admin\
**Password**: testdrive

Launch 3.4.0 Test Drive

Login at the top-right hand corner of the page

#### Open QuickSubmit plugin

Scroll down the left hand menu to find **Tools**

Click on **QuickSubmit Plugin**

#### Enter metadata for your article

It is your turn to go through the steps I demonstrated in Tuesday's class.

For the author email, use **none\@example.com**

This advice came from the [Better Practices in Journal Metadata Guide](https://docs.pkp.sfu.ca/metadata-practices/en/)

#### Export using Native XML Plugin

The Test Drive journal is overwritten every night. To save your work, and make it available for comparison to metadata created in other sessions, we need to export it.

Go to Tools at the bottom of the left-hand menu.

Open the Native XML Plugin.

Click on the Export Articles tab.

Select your article and export it.

Share the XML file (we'll figure out a way for you to submit it to us)
